import { Ubuntu, Ubuntu_Mono, Maven_Pro } from 'next/font/google';
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"], // Puedes especificar los subconjuntos que necesites
  weight:["300", "400", "500", "700"], // Puedes especificar los pesos que necesites
});

const ubuntuMono = Ubuntu_Mono({
  subsets: ["latin"], // Puedes especificar los subconjuntos que necesites
  weight:["400"], // Puedes especificar los pesos que necesites
});

const maven = Maven_Pro({
  subsets: ["latin"], // Puedes especificar los subconjuntos que necesites
  weight:["400", "500", "700"], // Puedes especificar los pesos que necesites
  variable: "Maven_Pro", // Puedes especificar el nombre de la variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${maven.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

